version: '3.9'

services:
  backend:
    build: ./Server
    container_name: django_server
    volumes:
      - ./Server:/app
    ports:
      - "8000:8000"
    # env_file:
    #   - ./Server/.env  # nếu có biến môi trường
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: healthdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
