version: '3.9'

services:
  backend:
    build: ./Server
    container_name: django_server
    volumes:
      - ./Server:/app
    ports:
      - "8000:8000"
    # env_file:
    #   - ./Server/.env  # nếu có biến môi trường
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: healthdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge