# Generated by Django 5.2.4 on 2025-07-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='insurance_number',
            field=models.CharField(blank=True, help_text='Số thẻ bảo hiểm y tế', max_length=50),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='medical_history',
            field=models.TextField(blank=True, help_text='Tiền sử bệnh án'),
        ),
    ]
