[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn config.wsgi:application"
healthcheckPath = "/api/health/"
healthcheckTimeout = 100

[env]
PYTHON_VERSION = "3.10.0"